lenguage:java
jdk:
  - openjdk11
  
branches:
  only:
    - master
script: 
  - C:\Travis\sale-system-app\ mvnw clean install 
notifications:
  email:
    recipients:
      - pcsimleo@upc.edu.pe
  
before_install:
  -chmod +x mvnw 
  
